### ISSUE TITLE
/table/ paths with 500 errors

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#162]
There are some tables/tabulations which result in 500 errors because of assumptions we made in wiring stuff up. Google Search Console helps flush out which. All of the below need to be investigated. Hopefully they boil down to a smaller number of problem cases.

http://censusreporter.org/tables/B06004/
http://censusreporter.org/tables/B08105/
http://censusreporter.org/tables/B08505/
http://censusreporter.org/tables/B15004/
http://censusreporter.org/tables/B18034/
http://censusreporter.org/tables/B22005/
http://censusreporter.org/tables/B23005/
http://censusreporter.org/tables/C07203/
http://censusreporter.org/tables/C05003B/
http://censusreporter.org/tables/C08017/
http://censusreporter.org/tables/C08602/
http://censusreporter.org/tables/C12002/

I'm tired of copy/pasting them. We should fix these and then see if the others are fixed by the same solutions.

**Comment by tuchandra** [comment]
These fall under issue #141, where the core table doesn't exist but iterations do (and #168 is a PR to fix this)
http://censusreporter.org/tables/B06004/
http://censusreporter.org/tables/B08105/
http://censusreporter.org/tables/B08505/

These straight up don't exist -- nor do the C tables or any iterations. I can't find anything to tell me where these links are intended to go.
http://censusreporter.org/tables/B15004/
http://censusreporter.org/tables/B18034/
http://censusreporter.org/tables/B22005/
http://censusreporter.org/tables/B23005/

For this one, the B table, C table, and B table iterations all exist, but the C table iterations do not (which is why this link doesn't work). However,the C table is not linked from the B tables, and the B tables are not linked from the C table (which is probably a separate issue).
http://censusreporter.org/tables/C05003B/

These have a B table (some with iterations) but no C table (nor is one linked anywhere), so I'm not sure how anyone is getting to these.
http://censusreporter.org/tables/C07203/
http://censusreporter.org/tables/C08017/
http://censusreporter.org/tables/C08602/
http://censusreporter.org/tables/C12002/

**Comment by tuchandra** [comment]
Update: the four in the second group (B15004, B18034, B22005, B23005) are linked on the [Poverty topics page](https://censusreporter.org/topics/poverty/) in the bottom section. How are the tables there generated?

**Comment by tuchandra** [comment]
Update on the last group, with a similar culprit: on the [Migration topics page](http://censusreporter.org/topics/migration/), it's said next to B07203 has a collapsed version (a C table) when it does not. Same with the [Commute topics page](http://censusreporter.org/topics/commute/) for B08017 and B08602. How is the notation that a collapsed table exists generated?

Unsure about where people are getting C12002, though, as the pages for the three topics under which B12002 falls do not list it.

**Comment by JoeGermuska** [comment]
@tuchandra the tables on the topics pages were generated from data, but not from current data. Tables sometimes get dropped. [This page](http://www.census.gov/programs-surveys/acs/technical-documentation/table-and-geography-changes.html) details the changes. In principle, I'd like to verify missing tables there, but the way those pages are organized, it's a little tedious.  

Ultimately, if the tables aren't in `census_tabulation_metadata` they should be removed from the topic pages. I'd love to maintain something at URLs for one-real-but-now-obsolete tables that explains what happened, but managing that data seems just a little more work than the real payoff for that.

**Comment by tuchandra** [comment]
I'm closing this, now that I've enumerated the cases and split them up. See #173, #174, #175, and #176 for the subtasks (also linked above).
