### ISSUE TITLE
Autosuggest thinking cities are addresses

### ISSUE THREAD

**Issue by tuchandra** [censusreporter/censusreporter#183]
The full text search autosuggest seems to be a bit overzealous when deciding that something is an address. Entering `columbus` at `/search-results/` lists a host of locations before any of the place entries. The same goes for `ithaca`, `los angeles`, `carmel`, and `chicago`. 

The behavior is inconsistent, though, and occasionally (but not frequently) it gives the places before the locations. I have noticed that if I type `naperville`, for instance, I see place results first; if I backspace a few characters to `naperv`, nothing changes; and if I re-complete it to `naperville` again, it gives locations first. If I go from one addresses-first set of results to typing in a completely new query, I get addresses first again.

**Comment by tuchandra** [comment]
I'm still trying and failing to exactly categorize the conditions under which this happens. Sometimes a particular query returns places / profiles first, other times locations; and I can't figure out why.

**Comment by Joonpark13** [comment]
This is because the current implementation [waits for both ajax requests to complete](https://github.com/censusreporter/censusreporter/blob/full-text-search/censusreporter/apps/census/static/js/full-text-autocomplete.js#L21), then loads the autosuggest. Will refactor to do them in sequence.

Upon discussion with @JoeGermuska we decided that we could just put the few location results at the top, but especially with searches like "chicago" I see that would not be the best option. Marking as enhancement and removing bug label accordingly.

**Comment by Joonpark13** [comment]
Commit 79ff3e8 addresses the ordering issue - locations now always show up before other page types. We should still think about if this is actually the best implementation, though.

**Comment by Joonpark13** [comment]
After discussion with @JoeGermuska we've decided to place locations after other page types. Making those changes now.
