### ISSUE TITLE
Downloads fail because of "doesn't include" error

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#200]
Related to #110 

A friend of the project is trying to download Median Income data for [places and ZCTAs in Michigan](https://censusreporter.org/data/table/?table=B19013&geo_ids=160%7C04000US26,860%7C04000US26&primary_geo_id=04000US26)

The Download link returns errors because not all of the geographies in those sets are in the latest release.  However, the link is on a page which shows all that data, so it's extra frustrating that it can't be downloaded.

Independent of my general frustration with #110, however it is possible for someone to see a table of data, the download link on that page should pass to the API download with the same details so that there's no error.

Also, after some URL hacking, I found that even specifying a release (like [ACS 2014-5yr places in Michigan](https://api.censusreporter.org/1.0/data/download/acs2014_5yr?table_ids=B19013&geo_ids=160|04000US26&format=csv) or [ACS 2014-5yr ZCTAs in Michigan](https://api.censusreporter.org/1.0/data/download/acs2014_5yr?table_ids=B19013&geo_ids=860|04000US26&format=csv), an error is returned because a singular geography is "not available" in that specific release.

This could be because of new geographies which are in ACS2015-1yr but not ACS2014-5yr — I haven't had time to check.

**Comment by JoeGermuska** [comment]
A [UserVoice report](https://censusreporter.uservoice.com/admin/tickets/225/?q=assignee%3Ame+status%3Aopen) ran into the "The ACS 2014 1-year release doesn't include GeoID(s)... ”. error

He was looking at B17002. He found that the data was in C17002 -- We should try to recognize when variant tables in a tabulation have data which isn't available for the first choice table.

**Comment by JoeGermuska** [comment]
[Another report](https://censusreporter.uservoice.com/admin/tickets/227) 
The URL which leads to the problem: http://censusreporter.org/data/table/?table=B07011&geo_ids=05000US12086,140|05000US12086,050|04000US12,05000US12086,860|05000US12086&primary_geo_id=05000US12086

**Comment by iandees** [comment]
I'm looking into this. The code in the download endpoint should be skipping to the 2015 5-year data (like the data view endpoint does), but is stopping and failing at the 2014 1-year for some reason.

**Comment by 24AheadDotCom** [comment]
This appears to still be an issue. For [this](https://24aheaddotcom.github.io/Newsom-zip-code-vaccine-tiers/) (if anyone wants to double-check my math, please do so), I just got the 'error' message in the JSON: "None of the releases had all the requested geo_ids: The ACS 2019 1-year release doesn't include GeoID(s) 86000US95842,86000US90022,86000US95825,86000US95192., The ACS 2019 5-year release doesn't include GeoID(s) 86000US95192." for [this](https://api.censusreporter.org/1.0/data/show/latest?table_ids=B01001&geo_ids=86000US95842,86000US95825,86000US90022,86000US95192). I had to sit in a loop, getting the data for each zip individually. Otherwise, out of 1100+ zips, 100 were missing when I tried to do them 10 at a time.

Only the data for zips 95192 and 92862 appears to be missing entirely (at least using 'latest').

**Comment by JoeGermuska** [comment]
@24AheadDotCom The issue you encountered is not the same as documented here.  

More specifically, you got an error because 95192 and 92862 are **not** ZIP Code Tabulation Areas. Not every ZIP Code has a matching ZIP Code Tabulation Area. This is a subtle nuance, but in short, about 10000 valid ZIP Codes do not have matching ZCTAs. There are strategies for associating non-ZCTA ZIP Codes with ZCTAs for the inevitable cases when you just need some data anyway, and we used one of those strategies to develop a crosswalk which you could use, [documented here.](https://github.com/censusreporter/acs-aggregate/blob/master/crosswalks/zip_to_zcta/ZIP_ZCTA_README.md)  (This is not part of the Census Reporter website directly).

at the level of using the download API URL, we will continue to expect people to only request downloads for valid geoIDs.
