### ISSUE TITLE
Qo.getComputedStyle is null error in Firefox

### ISSUE THREAD

**Issue by NYCJacob** [censusreporter/censusreporter#238]
Thanks for the website.  Trying to embed some charts and they are not appearing.  Seems to only effect Firefox.  Getting TypeError: QogetComputedStyle(...) is null  calling jquery@2.1,d3js@3.4

Looks like it might be related to a still open Firefox bug here 
https://bugzilla.mozilla.org/show_bug.cgi?id=548397

I  don't see anyone else having this issue however.
Do  not get the error in Chrome, but the charts are not displaying.

**Comment by ryanpitts** [comment]
Hi @NYCJacob, sorry that our embeds aren't working for you! Based on the Firefox bug you're linking, I'm wondering if there's a weird interaction going on with iframe styling on the page you're embedding the charts onto.

Does this [vanilla test of the embed code](https://censusreporter.org/static/embed.html) work in Firefox for you?

**Comment by NYCJacob** [comment]
the vanilla test does show for me in both chrome and firefox.  I have a test site up at http://142.93.14.50/  where I am using several embeds under the census tab.  The embeds do not render in either Chrome or Firefox.  Firefox console show these two messages:

Source map error: request failed with status 404 Resource URL: https://cdn.jsdelivr.net/g/jquery@2.1,d3js@3.4 Source Map URL: jquery.min.map

===========================
TypeError: Qo.getComputedStyle(...) is null[Learn More] jquery@2.1,d3js@3.4:10:9480
ya.style
https://cdn.jsdelivr.net/g/jquery@2.1,d3js@3.4:10:9480
Chart/chart.getParentHeight
https://s3.amazonaws.com/embed.censusreporter.org/1.0/js/charts.js:1186:25
Chart/chart.init
https://s3.amazonaws.com/embed.censusreporter.org/1.0/js/charts.js:24:30
Chart
https://s3.amazonaws.com/embed.censusreporter.org/1.0/js/charts.js:1262:5
makeEmbedFrame/embedFrame.makeChart
https://s3.amazonaws.com/embed.censusreporter.org/1.0/js/embed.chart.frame.js:60:37
makeEmbedFrame/embedFrame.getChartData/<
https://s3.amazonaws.com/embed.censusreporter.org/1.0/js/embed.chart.frame.js:51:17
j
https://cdn.jsdelivr.net/g/jquery@2.1,d3js@3.4:3:26920
fireWith
https://cdn.jsdelivr.net/g/jquery@2.1,d3js@3.4:3:27738
x
https://cdn.jsdelivr.net/g/jquery@2.1,d3js@3.4:5:11251
b/<
https://cdn.jsdelivr.net/g/jquery@2.1,d3js@3.4:5:14765

**Comment by JoeGermuska** [comment]
The error about the source map is an incidental warning, because we don't provide that -- source maps are a tool to facilitate debugging minified javascript, but they're not required for things to work.

I'm fairly certain that your issue has to do with the Census tab not being visible when the page is initialized. This is a common problem with tab interfaces, because things like the Census Reporter embeds need to know the size of their container to initialize, and the size in your implementation is zero. 

In Chrome, I find that if I switch the the Census tab and then resize the browser, the charts redraw correctly. In Firefox, they don't. In general, the approach would be either to have the Census tabs visible on page load, or to add some javascript so that when the census tab gets activated, either the CensusReporter embeds are added only after the tab is activated for the first time, or that some other behavior is added to make sure they know to resize themselves.

**Comment by NYCJacob** [comment]
OK that makes sense as the census content is not loaded by a jquery load() method.  I'll work on it.  Thank you very much!
